--
-- PostgreSQL database dump
--

\restrict QJairrY7so4NyZPJVM3hpUIAlPXZIjEhgnVK2nuzuUyqGnqtvXIvNSjR5yOANkp

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: discussion_post; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.discussion_post (
    id integer NOT NULL,
    inventory_id integer NOT NULL,
    message text NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE public.discussion_post OWNER TO inventory_user;

--
-- Name: discussion_post_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.discussion_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discussion_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discussion_post_likes; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.discussion_post_likes (
    id integer NOT NULL,
    liked_by_id integer NOT NULL,
    post_id integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.discussion_post_likes OWNER TO inventory_user;

--
-- Name: discussion_post_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.discussion_post_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discussion_post_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO inventory_user;

--
-- Name: inventories; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.inventories (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    category character varying(100) NOT NULL,
    image_url character varying(500) DEFAULT NULL::character varying,
    is_public boolean NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    owner_id integer NOT NULL
);


ALTER TABLE public.inventories OWNER TO inventory_user;

--
-- Name: inventories_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_access; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.inventory_access (
    id integer NOT NULL,
    role character varying(20) NOT NULL,
    inventory_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.inventory_access OWNER TO inventory_user;

--
-- Name: inventory_access_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.inventory_access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_fields; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.inventory_fields (
    id integer NOT NULL,
    type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    "position" integer NOT NULL,
    inventory_id integer NOT NULL
);


ALTER TABLE public.inventory_fields OWNER TO inventory_user;

--
-- Name: inventory_fields_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.inventory_fields ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_fields_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_item_field_values; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.inventory_item_field_values (
    id integer NOT NULL,
    value text,
    item_id integer NOT NULL,
    field_id integer NOT NULL
);


ALTER TABLE public.inventory_item_field_values OWNER TO inventory_user;

--
-- Name: inventory_item_field_values_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.inventory_item_field_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_item_field_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_items; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.inventory_items (
    id integer NOT NULL,
    custom_id character varying(255) NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    inventory_id integer NOT NULL,
    created_by_id integer NOT NULL
);


ALTER TABLE public.inventory_items OWNER TO inventory_user;

--
-- Name: inventory_items_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.inventory_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: inventory_user
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(255) DEFAULT NULL::character varying NOT NULL,
    is_admin boolean NOT NULL,
    is_blocked boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO inventory_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: inventory_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: discussion_post; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.discussion_post (id, inventory_id, message, created_at, author_id) FROM stdin;
9	10	Hello! I am a regular user	2025-12-17 06:58:06	13
\.


--
-- Data for Name: discussion_post_likes; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.discussion_post_likes (id, liked_by_id, post_id, created_at) FROM stdin;
8	13	9	2025-12-17 06:58:06
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20251213140953	2025-12-13 14:13:35	5
DoctrineMigrations\\Version20251214092529	2025-12-14 09:27:24	22
DoctrineMigrations\\Version20251214131302	2025-12-14 13:18:33	12
DoctrineMigrations\\Version20251215112657	2025-12-15 11:27:06	8
DoctrineMigrations\\Version20251215152825	2025-12-15 15:29:42	12
DoctrineMigrations\\Version20251215153317	2025-12-15 15:33:27	4
DoctrineMigrations\\Version20251215155023	2025-12-15 15:51:21	1
DoctrineMigrations\\Version20251216055403	2025-12-16 05:54:27	6
DoctrineMigrations\\Version20251216080450	2025-12-16 08:07:08	9
DoctrineMigrations\\Version20251216080956	2025-12-16 08:10:22	2
DoctrineMigrations\\Version20251216085251	2025-12-16 08:52:58	2
\.


--
-- Data for Name: inventories; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.inventories (id, title, description, category, image_url, is_public, version, created_at, updated_at, owner_id) FROM stdin;
10	Demo Inventory	Inventory created from fixtures	Demo	\N	t	1	2025-12-17 06:58:06	2025-12-17 06:58:06	12
\.


--
-- Data for Name: inventory_access; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.inventory_access (id, role, inventory_id, user_id) FROM stdin;
\.


--
-- Data for Name: inventory_fields; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.inventory_fields (id, type, title, "position", inventory_id) FROM stdin;
10	TEXT	Serial number	1	10
\.


--
-- Data for Name: inventory_item_field_values; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.inventory_item_field_values (id, value, item_id, field_id) FROM stdin;
\.


--
-- Data for Name: inventory_items; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.inventory_items (id, custom_id, version, created_at, updated_at, inventory_id, created_by_id) FROM stdin;
21	ITEM-00222	1	2025-12-17 11:30:40	2025-12-17 11:30:40	10	12
23	ITEM-003	1	2025-12-17 14:27:39	2025-12-17 14:27:39	10	12
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: inventory_user
--

COPY public.users (id, email, username, password, is_admin, is_blocked, created_at, updated_at) FROM stdin;
12	admin@test.com	admin	$2y$13$D69LtutRrAqx1hajRxkO2OqhQXOaZCmvPIIGNcQXCJWpnU5T15TdG	t	f	2025-12-17 06:58:05	2025-12-17 06:58:05
13	user@test.com	user	$2y$13$ZHbCfRBQUdbR9I1pVPqCY.ZC/MIuEBPEdFwF8DuxWjiAcb.hc9.qa	f	f	2025-12-17 06:58:06	2025-12-17 06:58:06
\.


--
-- Name: discussion_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.discussion_post_id_seq', 9, true);


--
-- Name: discussion_post_likes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.discussion_post_likes_id_seq', 8, true);


--
-- Name: inventories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.inventories_id_seq', 10, true);


--
-- Name: inventory_access_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.inventory_access_id_seq', 1, false);


--
-- Name: inventory_fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.inventory_fields_id_seq', 10, true);


--
-- Name: inventory_item_field_values_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.inventory_item_field_values_id_seq', 1, false);


--
-- Name: inventory_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.inventory_items_id_seq', 23, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inventory_user
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: discussion_post_likes discussion_post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post_likes
    ADD CONSTRAINT discussion_post_likes_pkey PRIMARY KEY (id);


--
-- Name: discussion_post discussion_post_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post
    ADD CONSTRAINT discussion_post_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: inventories inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_pkey PRIMARY KEY (id);


--
-- Name: inventory_access inventory_access_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_access
    ADD CONSTRAINT inventory_access_pkey PRIMARY KEY (id);


--
-- Name: inventory_fields inventory_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_fields
    ADD CONSTRAINT inventory_fields_pkey PRIMARY KEY (id);


--
-- Name: inventory_item_field_values inventory_item_field_values_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_item_field_values
    ADD CONSTRAINT inventory_item_field_values_pkey PRIMARY KEY (id);


--
-- Name: inventory_items inventory_items_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_2441da63126f525e; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_2441da63126f525e ON public.inventory_item_field_values USING btree (item_id);


--
-- Name: idx_2441da63443707b0; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_2441da63443707b0 ON public.inventory_item_field_values USING btree (field_id);


--
-- Name: idx_3d82424d9eea759; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_3d82424d9eea759 ON public.inventory_items USING btree (inventory_id);


--
-- Name: idx_3d82424db03a8386; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_3d82424db03a8386 ON public.inventory_items USING btree (created_by_id);


--
-- Name: idx_5c5a508e4b89032c; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_5c5a508e4b89032c ON public.discussion_post_likes USING btree (post_id);


--
-- Name: idx_5c5a508eb4622ec2; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_5c5a508eb4622ec2 ON public.discussion_post_likes USING btree (liked_by_id);


--
-- Name: idx_6b5b7ff9eea759; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_6b5b7ff9eea759 ON public.inventory_access USING btree (inventory_id);


--
-- Name: idx_6b5b7ffa76ed395; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_6b5b7ffa76ed395 ON public.inventory_access USING btree (user_id);


--
-- Name: idx_7e397f239eea759; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_7e397f239eea759 ON public.inventory_fields USING btree (inventory_id);


--
-- Name: idx_7fe4c0bb9eea759; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_7fe4c0bb9eea759 ON public.discussion_post USING btree (inventory_id);


--
-- Name: idx_7fe4c0bbf675f31b; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_7fe4c0bbf675f31b ON public.discussion_post USING btree (author_id);


--
-- Name: idx_936c863d7e3c61f9; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE INDEX idx_936c863d7e3c61f9 ON public.inventories USING btree (owner_id);


--
-- Name: uniq_1483a5e9e7927c74; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE UNIQUE INDEX uniq_1483a5e9e7927c74 ON public.users USING btree (email);


--
-- Name: uniq_1483a5e9f85e0677; Type: INDEX; Schema: public; Owner: inventory_user
--

CREATE UNIQUE INDEX uniq_1483a5e9f85e0677 ON public.users USING btree (username);


--
-- Name: discussion_post_likes fk_5c5a508e4b89032c; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post_likes
    ADD CONSTRAINT fk_5c5a508e4b89032c FOREIGN KEY (post_id) REFERENCES public.discussion_post(id) ON DELETE CASCADE;


--
-- Name: discussion_post_likes fk_5c5a508eb4622ec2; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post_likes
    ADD CONSTRAINT fk_5c5a508eb4622ec2 FOREIGN KEY (liked_by_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: inventory_access fk_6b5b7ff9eea759; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_access
    ADD CONSTRAINT fk_6b5b7ff9eea759 FOREIGN KEY (inventory_id) REFERENCES public.inventories(id) ON DELETE CASCADE;


--
-- Name: inventory_access fk_6b5b7ffa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_access
    ADD CONSTRAINT fk_6b5b7ffa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: discussion_post fk_7fe4c0bb9eea759; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post
    ADD CONSTRAINT fk_7fe4c0bb9eea759 FOREIGN KEY (inventory_id) REFERENCES public.inventories(id) ON DELETE CASCADE;


--
-- Name: discussion_post fk_discussion_post_author; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.discussion_post
    ADD CONSTRAINT fk_discussion_post_author FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: inventory_fields fk_field_inventory; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_fields
    ADD CONSTRAINT fk_field_inventory FOREIGN KEY (inventory_id) REFERENCES public.inventories(id) ON DELETE CASCADE;


--
-- Name: inventories fk_inventory_owner; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT fk_inventory_owner FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: inventory_items fk_item_creator; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT fk_item_creator FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- Name: inventory_items fk_item_inventory; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT fk_item_inventory FOREIGN KEY (inventory_id) REFERENCES public.inventories(id) ON DELETE CASCADE;


--
-- Name: inventory_item_field_values fk_value_field; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_item_field_values
    ADD CONSTRAINT fk_value_field FOREIGN KEY (field_id) REFERENCES public.inventory_fields(id) ON DELETE CASCADE;


--
-- Name: inventory_item_field_values fk_value_item; Type: FK CONSTRAINT; Schema: public; Owner: inventory_user
--

ALTER TABLE ONLY public.inventory_item_field_values
    ADD CONSTRAINT fk_value_item FOREIGN KEY (item_id) REFERENCES public.inventory_items(id) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO inventory_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO inventory_user;


--
-- PostgreSQL database dump complete
--

\unrestrict QJairrY7so4NyZPJVM3hpUIAlPXZIjEhgnVK2nuzuUyqGnqtvXIvNSjR5yOANkp

