<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251214092529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial inventory schema with constraints and indexes';
    }

    public function up(Schema $schema): void
    {
        // inventories
        $this->addSql('
            CREATE TABLE inventories (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                description TEXT NOT NULL,
                category VARCHAR(100) NOT NULL,
                image_url VARCHAR(500) DEFAULT NULL,
                is_public BOOLEAN NOT NULL,
                version INT DEFAULT 1 NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                owner_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('CREATE INDEX idx_inventory_owner ON inventories (owner_id)');
        $this->addSql('CREATE INDEX idx_inventory_public ON inventories (is_public)');

        // inventory_fields
        $this->addSql('
            CREATE TABLE inventory_fields (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                type VARCHAR(50) NOT NULL,
                title VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                show_in_table BOOLEAN NOT NULL,
                position INT NOT NULL,
                inventory_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('CREATE INDEX idx_field_inventory ON inventory_fields (inventory_id)');
        $this->addSql('CREATE INDEX idx_field_type ON inventory_fields (type)');

        // inventory_items
        $this->addSql('
            CREATE TABLE inventory_items (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                custom_id VARCHAR(255) NOT NULL,
                version INT DEFAULT 1 NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                inventory_id INT NOT NULL,
                created_by_id INT NOT NULL,
                PRIMARY KEY (id),
                CONSTRAINT uniq_inventory_custom_id UNIQUE (inventory_id, custom_id)
            )
        ');
        $this->addSql('CREATE INDEX idx_item_inventory ON inventory_items (inventory_id)');
        $this->addSql('CREATE INDEX idx_item_created_by ON inventory_items (created_by_id)');

        // inventory_item_field_values
        $this->addSql('
            CREATE TABLE inventory_item_field_values (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                value TEXT DEFAULT NULL,
                item_id INT NOT NULL,
                field_id INT NOT NULL,
                PRIMARY KEY (id),
                CONSTRAINT uniq_item_field UNIQUE (item_id, field_id)
            )
        ');
        $this->addSql('CREATE INDEX idx_value_item ON inventory_item_field_values (item_id)');
        $this->addSql('CREATE INDEX idx_value_field ON inventory_item_field_values (field_id)');

        // foreign keys
        $this->addSql('ALTER TABLE inventories ADD CONSTRAINT fk_inventory_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_fields ADD CONSTRAINT fk_field_inventory FOREIGN KEY (inventory_id) REFERENCES inventories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_items ADD CONSTRAINT fk_item_inventory FOREIGN KEY (inventory_id) REFERENCES inventories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_items ADD CONSTRAINT fk_item_creator FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_item_field_values ADD CONSTRAINT fk_value_item FOREIGN KEY (item_id) REFERENCES inventory_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_item_field_values ADD CONSTRAINT fk_value_field FOREIGN KEY (field_id) REFERENCES inventory_fields (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inventory_item_field_values');
        $this->addSql('DROP TABLE inventory_items');
        $this->addSql('DROP TABLE inventory_fields');
        $this->addSql('DROP TABLE inventories');
    }
}
