<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251215152825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discussion_post_likes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, liked_by_id INT NOT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C5A508EB4622EC2 ON discussion_post_likes (liked_by_id)');
        $this->addSql('CREATE INDEX IDX_5C5A508E4B89032C ON discussion_post_likes (post_id)');
        $this->addSql('ALTER TABLE discussion_post_likes ADD CONSTRAINT FK_5C5A508EB4622EC2 FOREIGN KEY (liked_by_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post_likes ADD CONSTRAINT FK_5C5A508E4B89032C FOREIGN KEY (post_id) REFERENCES discussion_post (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE discussion_post_likes DROP CONSTRAINT FK_5C5A508EB4622EC2');
        $this->addSql('ALTER TABLE discussion_post_likes DROP CONSTRAINT FK_5C5A508E4B89032C');
        $this->addSql('DROP TABLE discussion_post_likes');
    }
}
