<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251215112657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FE4C0BB9EEA759 ON discussion_post (inventory_id)');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_7FE4C0BB9EEA759 FOREIGN KEY (inventory_id) REFERENCES inventories (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE discussion_post DROP CONSTRAINT FK_7FE4C0BB9EEA759');
        $this->addSql('DROP TABLE discussion_post');
    }
}
