<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Fixed migration for PostgreSQL:
 * - DROP CONSTRAINT instead of DROP INDEX for UNIQUE constraints
 * - Safe order of operations
 */
final class Version20251214131302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add inventory_access table and fix indexes/constraints for PostgreSQL';
    }

    public function up(Schema $schema): void
    {
        // -------------------------
        // inventory_access table
        // -------------------------
        $this->addSql(
            'CREATE TABLE inventory_access (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                role VARCHAR(20) NOT NULL,
                inventory_id INT NOT NULL,
                user_id INT NOT NULL,
                PRIMARY KEY (id)
            )'
        );

        $this->addSql(
            'CREATE INDEX IDX_6B5B7FF9EEA759 ON inventory_access (inventory_id)'
        );
        $this->addSql(
            'CREATE INDEX IDX_6B5B7FFA76ED395 ON inventory_access (user_id)'
        );

        $this->addSql(
            'ALTER TABLE inventory_access
             ADD CONSTRAINT FK_6B5B7FF9EEA759
             FOREIGN KEY (inventory_id) REFERENCES inventories (id)
             ON DELETE CASCADE'
        );

        $this->addSql(
            'ALTER TABLE inventory_access
             ADD CONSTRAINT FK_6B5B7FFA76ED395
             FOREIGN KEY (user_id) REFERENCES users (id)
             ON DELETE CASCADE'
        );

        // -------------------------
        // inventories indexes
        // -------------------------
        $this->addSql('DROP INDEX IF EXISTS idx_inventory_public');
        $this->addSql(
            'ALTER INDEX IF EXISTS idx_inventory_owner
             RENAME TO IDX_936C863D7E3C61F9'
        );

        // -------------------------
        // inventory_fields indexes
        // -------------------------
        $this->addSql('DROP INDEX IF EXISTS idx_field_type');
        $this->addSql(
            'ALTER INDEX IF EXISTS idx_field_inventory
             RENAME TO IDX_7E397F239EEA759'
        );

        // -------------------------
        // inventory_item_field_values
        // -------------------------
        // ❗ UNIQUE CONSTRAINT, not index
        $this->addSql(
            'ALTER TABLE inventory_item_field_values
             DROP CONSTRAINT IF EXISTS uniq_item_field'
        );

        $this->addSql(
            'ALTER INDEX IF EXISTS idx_value_item
             RENAME TO IDX_2441DA63126F525E'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS idx_value_field
             RENAME TO IDX_2441DA63443707B0'
        );

        // -------------------------
        // inventory_items
        // -------------------------
        // ❗ UNIQUE CONSTRAINT, not index
        $this->addSql(
            'ALTER TABLE inventory_items
             DROP CONSTRAINT IF EXISTS uniq_inventory_custom_id'
        );

        $this->addSql(
            'ALTER INDEX IF EXISTS idx_item_inventory
             RENAME TO IDX_3D82424D9EEA759'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS idx_item_created_by
             RENAME TO IDX_3D82424DB03A8386'
        );
    }

    public function down(Schema $schema): void
    {
        // -------------------------
        // inventory_access
        // -------------------------
        $this->addSql(
            'ALTER TABLE inventory_access
             DROP CONSTRAINT IF EXISTS FK_6B5B7FF9EEA759'
        );
        $this->addSql(
            'ALTER TABLE inventory_access
             DROP CONSTRAINT IF EXISTS FK_6B5B7FFA76ED395'
        );
        $this->addSql('DROP TABLE IF EXISTS inventory_access');

        // -------------------------
        // inventories
        // -------------------------
        $this->addSql(
            'CREATE INDEX idx_inventory_public ON inventories (is_public)'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_936C863D7E3C61F9
             RENAME TO idx_inventory_owner'
        );

        // -------------------------
        // inventory_fields
        // -------------------------
        $this->addSql(
            'CREATE INDEX idx_field_type ON inventory_fields (type)'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_7E397F239EEA759
             RENAME TO idx_field_inventory'
        );

        // -------------------------
        // inventory_item_field_values
        // -------------------------
        $this->addSql(
            'ALTER TABLE inventory_item_field_values
             ADD CONSTRAINT uniq_item_field
             UNIQUE (item_id, field_id)'
        );

        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_2441DA63126F525E
             RENAME TO idx_value_item'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_2441DA63443707B0
             RENAME TO idx_value_field'
        );

        // -------------------------
        // inventory_items
        // -------------------------
        $this->addSql(
            'ALTER TABLE inventory_items
             ADD CONSTRAINT uniq_inventory_custom_id
             UNIQUE (inventory_id, custom_id)'
        );

        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_3D82424D9EEA759
             RENAME TO idx_item_inventory'
        );
        $this->addSql(
            'ALTER INDEX IF EXISTS IDX_3D82424DB03A8386
             RENAME TO idx_item_created_by'
        );
    }
}
